name: tekartik_midi
version: 0.4.1
description: midi event and file parser
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  collection: any
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart3a
    version: '>=0.10.7'

dev_dependencies:
  test: any
  path: any
  build_runner: '>=0.9.0'
  build_test: '>=0.10.2'
  process_run: '>=0.10.2'
  dev_build: '>0.13.1+1'
  build_web_compilers: '>=0.4.0'

